<script lang="ts">
	import { page } from '$app/state';
	import { currentLocale } from '$lib/locale';
	import { locales, localizeHref } from '$lib/paraglide/runtime';

	interface Props {
		title: string;
		description?: string;
		image?: string | null;
		/** "article" for news posts, otherwise a normal page. */
		type?: 'website' | 'article';
		publishedAt?: Date | null;
		noindex?: boolean;
	}

	let {
		title,
		description = '',
		image = null,
		type = 'website',
		publishedAt = null,
		noindex = false
	}: Props = $props();

	const siteName = 'AWS User Group Lao';

	/*
	 * The brand lockup on the brand navy, generated by
	 * scripts/generate-brand-assets.mjs. Pages without a cover image fell back to
	 * a bare `summary` card before this — a shared link showed no image at all.
	 */
	const fallbackImage = '/og-default.png';

	let fullTitle = $derived(title === siteName ? title : `${title} — ${siteName}`);
	let canonical = $derived(new URL(page.url.pathname, page.url.origin).href);
	let ogImage = $derived(new URL(image ?? fallbackImage, page.url.origin).href);
</script>

<svelte:head>
	<title>{fullTitle}</title>
	{#if description}
		<meta name="description" content={description} />
	{/if}
	{#if noindex}
		<meta name="robots" content="noindex, nofollow" />
	{/if}
	<link rel="canonical" href={canonical} />

	<!--
		Tells search engines the two language versions are the same page, so they
		are not treated as duplicates and the right one is served per audience.
	-->
	{#each locales as locale (locale)}
		<link
			rel="alternate"
			hreflang={locale}
			href={new URL(localizeHref(page.url.pathname, { locale }), page.url.origin).href}
		/>
	{/each}

	<meta property="og:site_name" content={siteName} />
	<meta property="og:type" content={type} />
	<meta property="og:title" content={fullTitle} />
	<meta property="og:url" content={canonical} />
	<meta property="og:locale" content={currentLocale() === 'lo' ? 'lo_LA' : 'en_GB'} />
	{#if description}
		<meta property="og:description" content={description} />
	{/if}
	{#if ogImage}
		<meta property="og:image" content={ogImage} />
		<meta name="twitter:card" content="summary_large_image" />
	{:else}
		<meta name="twitter:card" content="summary" />
	{/if}
	{#if type === 'article' && publishedAt}
		<meta property="article:published_time" content={publishedAt.toISOString()} />
	{/if}
</svelte:head>
